# Generated by Django 5.1.4 on 2025-01-11 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_comment_total_replies_alter_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='to_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='to_decision',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='to_membership',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='to_need',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='to_report',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='to_task',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
